version: '3.3'

services:
    api:
        image: pokemon-trainer-api
        build:
            context: .
            dockerfile: ./dockerfile
        ports:
            - 3000:3000
        environment:
          - DB_HOST=db
          - DB_PORT=5432
          - DB_USERNAME=postgres
          - DB_PASSWORD=postgres
          - DB_DATABASE=postgres
          - JWT_SECRET=supersecret
        restart: unless-stopped
        depends_on:
            - db
    db:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      restart: unless-stopped